### ISSUE TITLE
UnhandledPromiseRejectionWarning when quitting challenge creation script

### ISSUE THREAD

**Issue by jasminexie** [jasminexie/100-days-css#1]
UnhandledPromiseRejectionWarning when quitting challenge creation script (`npm run new`)

```
(node:12823) UnhandledPromiseRejectionWarning
(node:12823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12823) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Expected behavior: graceful exit without errors

**Comment by guesant** [comment]
Helo, Jamine!

_"promises (async or await) without try/catch block will terminate the Node.js process"_

Just add a `.catch(() => {})` block after async call, like:
```js
(async function main() {
  // ...
})().catch(() => {});
```

----

Can i make a PR or you will fix this?

**Comment by jasminexie** [comment]
> Helo, Jasmine!
> 
> _"promises (async or await) without try/catch block will terminate the Node.js process"_
> 
> Just add a `.catch(() => {})` block after async call, like:
> 
> ```js
> (async function main() {
>   // ...
> })().catch(() => {});
> ```
> 
> Can i make a PR or you will fix this?

Thank you! I've been busy lately so this is something that I've found but haven't gotten around to do.

Personally I don't like chaining a `catch` after the function call; the point of writing an IFFE on server side is encapsulation but mostly cleanliness. Chaining `catch` after the IFFE would go against the pattern; while it *works*, it may not be the best idea design-wise.

What I'd rather do is 1. handle errors in a try-catch block, or 2. explicitly write `main()` as a promise and use the promise-style `catch` chaining you've mentioned. There are also libraries as [await-to-js](https://www.npmjs.com/package/await-to-js) that have their own methodology in error handling. Anything that scales, is consistent and clear will be great. You're welcome to make a PR.
