### ISSUE TITLE
Display the date of each challenge completed in `index.html`

### ISSUE THREAD

**Issue by jasminexie** [jasminexie/100-days-css#2]
In the main `index.html`, I'd like to display the date of each challenge completed, and their author. I have a few ideas:

* Read all git commit messages in the pre-commit hook. Since commit messages are mostly `feat: ${challenge-id}`, it wouldn't be difficult to parse the challenge name, commit date, and author id/email.
* Modify the structure of the existing `config.json`, and change how the Vue component reads `config.json`. We can do something like this:
    
    config.json
    ```
    [{
      "id": "012",
      "author": "jasminexie"
      "date": "09/01/2019"
    }]
    ```
    
    and display these details on the index page.

**Comment by guesant** [comment]
The date is in `DD/MM/YYYY` or `MM/DD/YYYY`?

**Comment by guesant** [comment]
@jasminexie I believe I can help you with this issue. Can I work on this?

**Comment by jasminexie** [comment]
> @jasminexie I believe I can help you with this issue. Can I work on this?

Great. I'll assign this to you.

The date format isn't very important - where I live it's usually MM/DD, but anything universally understood is OK. Since I'm currently the only person working on the repo, if you take a look at the git log you could probably see that all commit messages are somewhat consistent.

(If we're going to do this, we could try and enforce the `feat: ${challenge-id}` style commit message in a pre-commit hook. Just a thought.)

I haven't thought too much about the implementation, so if you want to work on this you have a LOT of freedom.

**Comment by guesant** [comment]
Oh thanks!

Do you have a style for this information in mind? If you want I can send you some suggestions

**Comment by jasminexie** [comment]
> Oh thanks!
> 
> Do you have a style for this information in mind? If you want I can send you some suggestions

All suggestions are welcome 👍

What do you mean by styles? If you're referring to the styling and layout of the final result - anything clear and consistent is fine. I've used [element-ui](https://element.eleme.cn/#/en-US); you're welcome to adopt another UI library or write your own styles.

**Comment by guesant** [comment]
Yeah, i mean style like design/layout of the information about author and date. I'm not fluent in english, sorry 😅🙃.

It's amazing the CSS work you did 👏👏👏. I will soon accept the "100 Days of CSS" challenge using this project as the results manager 😁

----

I've been thinking of something simple, like this:

![op1](https://user-images.githubusercontent.com/43099880/65825310-81cea300-e243-11e9-94d3-e16764542333.png)
![op2](https://user-images.githubusercontent.com/43099880/65825311-81cea300-e243-11e9-8b5d-e2589d1988f9.png)

What do you think about it?

**Comment by jasminexie** [comment]
I've looked at the code and you've done a really good job. It's nice to see such a high-quality contribution 😄

Both styles look good! I personally like the second one better. I'll be happy to merge this once Hacktoberfest begins.

**Comment by guesant** [comment]
Can I make two separate PR? First for generate config and second to display the info?
